jumpserver/urls.py
# ~*~ coding: utf-8 ~*~
from __future__ import unicode_literals

from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from .views import IndexView, LunaView, I18NView, HealthCheckView
from .swagger import get_swagger_view

api_v1 = [
   path('users/v1/', include('users.urls.api_urls', namespace='api-users')),
   path('assets/v1/', include('assets.urls.api_urls', namespace='api-assets')),
   path('perms/v1/', include('perms.urls.api_urls', namespace='api-perms')),
   path('terminal/v1/', include('terminal.urls.api_urls', namespace='api-terminal')),
   path('ops/v1/', include('ops.urls.api_urls', namespace='api-ops')),
   path('audits/v1/', include('audits.urls.api_urls', namespace='api-audits')),
   path('orgs/v1/', include('orgs.urls.api_urls', namespace='api-orgs')),
   path('settings/v1/', include('settings.urls.api_urls', namespace='api-settings')),
   path('authentication/v1/', include('authentication.urls.api_urls', namespace='api-auth')),
   path('common/v1/', include('common.urls.api_urls', namespace='api-common')),
   path('applications/v1/', include('applications.urls.api_urls', namespace='api-applications')),
   path('extra_app/deploy/v1/', include('deploy.urls.api_urls', namespace='api-deploy')),
   path('extra_app/dreport/v1/', include('dreport.urls.api_urls', namespace='api-dreport')),
   path('extra_app/devops/v1/', include('devops.urls.api_urls', namespace='api-devops')),
   path('dbops/v1/', include('dbops.urls.api_urls', namespace='api-dbops')),
]

api_v2 = [
   path('terminal/v2/', include('terminal.urls.api_urls_v2', namespace='api-terminal-v2')),
   path('users/v2/', include('users.urls.api_urls_v2', namespace='api-users-v2')),
]


app_view_patterns = [
    path('users/', include('users.urls.views_urls', namespace='users')),
    path('assets/', include('assets.urls.views_urls', namespace='assets')),
    path('perms/', include('perms.urls.views_urls', namespace='perms')),
    path('terminal/', include('terminal.urls.views_urls', namespace='terminal')),
    path('ops/', include('ops.urls.view_urls', namespace='ops')),
    path('audits/', include('audits.urls.view_urls', namespace='audits')),
    path('orgs/', include('orgs.urls.views_urls', namespace='orgs')),
    path('auth/', include('authentication.urls.view_urls'), name='auth'),
    path('applications/', include('applications.urls.views_urls', namespace='applications')),
    path('extra_app/deploy/', include('deploy.urls.views_urls', namespace='deploy')),
    path('extra_app/', include('dreport.urls.views_urls', namespace='dreport')),
    path('extra_app/', include('devops.urls.views_urls', namespace='devops')),
    path('dbops/', include('dbops.urls.views_urls', namespace='dbops')),
]


if settings.XPACK_ENABLED:
    app_view_patterns.append(
        path('xpack/', include('xpack.urls.view_urls', namespace='xpack'))
    )
    api_v1.append(
        path('xpack/v1/', include('xpack.urls.api_urls', namespace='api-xpack'))
    )

js_i18n_patterns = i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)

api_v1_patterns = [
    path('api/', include(api_v1))
]

api_v2_patterns = [
    path('api/', include(api_v2))
]

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('', include(api_v2_patterns)),
    path('', include(api_v1_patterns)),
    path('api/health/', HealthCheckView.as_view(), name="health"),
    path('luna/', LunaView.as_view(), name='luna-view'),
    path('i18n/<str:lang>/', I18NView.as_view(), name='i18n-switch'),
    path('settings/', include('settings.urls.view_urls', namespace='settings')),
    # path('api/v2/', include(api_v2_patterns)),

    # External apps url
    path('captcha/', include('captcha.urls')),
]

urlpatterns += app_view_patterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
            + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += js_i18n_patterns

handler404 = 'jumpserver.error_views.handler404'
handler500 = 'jumpserver.error_views.handler500'

if settings.DEBUG:
    urlpatterns += [
        re_path('^swagger(?P<format>\.json|\.yaml)$',
                get_swagger_view().without_ui(cache_timeout=1), name='schema-json'),
        path('docs/', get_swagger_view().with_ui('swagger', cache_timeout=1), name="docs"),
        path('redoc/', get_swagger_view().with_ui('redoc', cache_timeout=1), name='redoc'),

        re_path('^v2/swagger(?P<format>\.json|\.yaml)$',
                get_swagger_view().without_ui(cache_timeout=1), name='schema-json'),
        path('docs/v2/', get_swagger_view("v2").with_ui('swagger', cache_timeout=1), name="docs"),
        path('redoc/v2/', get_swagger_view("v2").with_ui('redoc', cache_timeout=1), name='redoc'),
    ]

devops/models/playbook.py
import uuid
import json
import os
import datetime
import yaml
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from common.utils import get_logger
from devops.ansible.runner import PlayBookRunner
from devops.ansible.runner import get_default_options
from ops.inventory import JMSInventory
from ops.ansible import AnsibleError


logger = get_logger(__file__)


playbook_dir = os.path.join(settings.PROJECT_DIR, 'data', 'playbooks')

if not os.path.isdir(playbook_dir):
    os.makedirs(playbook_dir)


class AnsibleRole(models.Model):

    name = models.CharField(max_length=200, verbose_name=_('Name'))
    add_time = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=128, blank=True, null=True, default='')
    desc = models.TextField(verbose_name="使用说明", blank=True, null=True, default='')

    def __str__(self):
        return str(self.name) + '(创建者:'+str(self.created_by)+')'


class PlayBookTask(models.Model):

    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    name = models.CharField(max_length=128, unique=True, verbose_name=_('Name'))
    created_by = models.CharField(max_length=128, blank=True, null=True, default='')
    date_created = models.DateTimeField(auto_now_add=True)
    desc = models.TextField(null=True, blank=True, verbose_name=_('Description'))
    ansible_role = models.ForeignKey(
        AnsibleRole, verbose_name=_('Ansible Role'), related_name='task',
        on_delete=models.DO_NOTHING
    )
    run_as_admin = models.BooleanField(default=False, verbose_name=_('Run as admin'))
    run_as = models.CharField(max_length=128, default='', verbose_name=_("Run as"))
    playbook_path = models.CharField(max_length=1000, verbose_name=_('Playbook Path'), blank=True, null=True)
    is_running = models.BooleanField(default=False, verbose_name=_('Is running'))
    extra_vars = models.CharField(max_length=512, verbose_name=_('Extra Vars'), blank=True, null=True)
    assets = models.ManyToManyField('assets.Asset', blank=True, verbose_name=_("Assets"))
    _hosts = models.TextField(blank=True, verbose_name=_('Hosts'))  # ['hostname1', 'hostname2']

    @property
    def hosts(self):
        return json.loads(self._hosts)

    @hosts.setter
    def hosts(self, item):
        self._hosts = json.dumps(item)

    # 获取默认options
    @property
    def options(self):
        return get_default_options()

    # 使用JMSInventory构建inventory
    @property
    def inventory(self):
        return JMSInventory(
            assets=self.assets.all(),
            run_as_admin=self.run_as_admin,
            run_as=self.run_as,
            become_info=None
        )

    @property
    def hex_id(self):
        return self.id.hex

    def create_playbook(self, ansible_role):
        self.playbook_path = os.path.join(playbook_dir, self.hex_id + '.yml')
        yml_tpl = [{'hosts': 'all', 'roles': [{'role': ansible_role.name}]}]
        with open(self.playbook_path, 'wt') as fhandler:
            yaml.dump(yml_tpl, fhandler)
        self.save()
        return True

    def record(self, result="", error=None):
        hid = str(uuid.uuid4())
        total_num = 0
        success_num = 0
        failed_num = 0
        summery_result = ""

        if result:

            for host, value in result.get('stats').items():
                total_num += value['ok'] + value['failures'] + value['unreachable']
                success_num += value['ok']
                failed_num += value['failures']

            plays = result.get('plays')

            for play in plays:
                tasks = play.get('tasks')
                for task in tasks:
                    # print(task)
                    title = 'Task: ' + task.get('task')['name']
                    summery_result += title
                    print(title)
                    hosts = task.get('hosts')
                    for hostname, r in hosts.items():
                        if r.get('stderr'):
                            error_msg = r.get('stderr')
                            line = "{}:{}\n".format(hostname, error_msg[0:100])
                        elif r.get('stdout'):
                            line = "{}:{}...\n".format(hostname, r.get('stdout')[0:50])
                        else:
                            line = "{}:{}\n".format(hostname, "sucess")
                        if not r.get('skipped_reason'):
                            summery_result += line
                            print(line)

        if result and not error:
            if failed_num == 0:
                exe_result = 'success'
            else:
                exe_result = 'failed'
            history = TaskHistory.objects.create(
                id=hid,
                task=self,
                exe_result=exe_result,
                result_info=summery_result,
                result_summary=json.dumps(result.get('stats')),
                total_num=total_num,
                success_num=success_num,
                failed_num=failed_num
            )
            logger.info("创建{}历史记录成功".format(history.id))
        elif error and result:
            history = TaskHistory.objects.create(
                id=hid,
                task=self,
                exe_result='failed',
                result_info=result,
                result_summary=json.dumps(result.get('stats')),
                total_num=total_num,
                success_num=success_num,
                failed_num=failed_num
            )
            logger.error("创建{}错误历史记录成功".format(history.id))

    def run(self):
        return self._run_only()

    def _run_only(self):
        date_start = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        logger.info("{} Start task: {}\r\n".format(date_start, self.name))
        self.is_running = True
        self.save()

        options = self.options

        if not self.playbook_path:
            self.create_playbook(self.ansible_role)

        # 判断playbook是否存在
        if not os.path.exists(self.playbook_path) or not os.path.isfile(self.playbook_path):
            logger.error("Role File Not Found!\nPlease check playbook_path: {}.".format(self.playbook_path))
            self.create_playbook(self.ansible_role)
            # self.is_running = False
            # self.save()
            # raise FileNotFoundError('Please check playbook_path {}.'.format(self.playbook_path))

        # 将playbook_path传入options
        # options = options._replace(playbook_path=self.playbook_path)
        options['playbook_path'] = self.playbook_path
        # 将task name传入start_at_task
        # options['start_at_task'] = self.name
        logger.debug(options)
        runner = PlayBookRunner(inventory=self.inventory, options=options)

        # 将额外变量传入变量控制器
        if self.extra_vars:
            runner.variable_manager._extra_vars = eval(self.extra_vars)
            logger.debug(json.dumps(runner.variable_manager.get_vars()))
        try:
            result = runner.run()
            logger.debug(json.dumps(result, indent=4))
            logger.info(json.dumps(result.get('stats'), indent=4))
            self.record(result)
            self.is_running = False
            self.save()
            # logger.info(json.dumps(result.get('stats'), indent=4))
            date_end = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            logger.info("\r\n{} Task finished".format(date_end))
            return result
        except AnsibleError as e:
            self.record(error=True, result=str(e))
            self.is_running = False
            self.save()
            date_end = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            logger.info("\r\n{} Task finished".format(date_end))
            logger.warn("Failed run playbook {}, {}".format(self.name, e))

    def __str__(self):
        return self.name


class TaskHistory(models.Model):

    id = models.UUIDField(uuid.uuid4, primary_key=True)
    task = models.ForeignKey(PlayBookTask, verbose_name="Task", on_delete=models.CASCADE)
    exe_result = models.CharField(max_length=10, choices=(
        ('success', '执行成功'), ('failed', '执行失败'), ('warning', '异常执行'),
        ('unrun', '未执行'), ('running', '正在执行')), default='unrun', verbose_name="任务状态")
    result_info = models.TextField(null=True, blank=True, verbose_name="任务结果详情")
    result_summary = models.TextField(null=True, blank=True, verbose_name="任务结果简要")
    total_num = models.IntegerField(null=True, blank=True, verbose_name="执行总数")
    success_num = models.IntegerField(null=True, blank=True, verbose_name="成功执行总数")
    failed_num = models.IntegerField(null=True, blank=True, verbose_name="失败执行总数")
    create_time = models.DateTimeField(auto_now_add=True)
    _hosts = models.TextField(null=True, blank=True, verbose_name=_('Hosts'))  # ['hostname1': {}, 'hostname2': {}]

    @property
    def failed_host(self):
        failed_host = []
        if self.result_summary:
            summary = json.loads(self.result_summary)
            for host, value in summary.items():
                if value["failures"] != 0 or value["unreachable"] != 0:
                    failed_host.append(host)
        return failed_host

    @property
    def success_host(self):
        success_host = []
        if self.result_summary:
            summary = json.loads(self.result_summary)
            for host, value in summary.items():
                if value["failures"] == 0 and value["unreachable"] == 0:
                    success_host.append(host)
        return success_host

    @property
    def short_id(self):
        return str(self.id).split('-')[-1]

    @property
    def hosts(self):
        return json.loads(self._hosts)

    @hosts.setter
    def hosts(self, item):
        self._hosts = json.dumps(item)

    class Meta:
        verbose_name = '任务历史'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}(执行时间{})'.format(self.task.name, self.create_time)

devops/models/task.py
import uuid
from django.db import models

from ops.models import AdHoc
from devops.models import PlayBookTask
from common.utils import get_logger
from deploy.models import DeployVersion

logger = get_logger(__file__)


class MainTask(models.Model):
    """
    任务中心: 任务列表
    """
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    name = models.CharField(max_length=128, unique=True, verbose_name="任务名称")
    desc = models.TextField(null=True, blank=True, verbose_name="任务简要")
    adhoc_task = models.ManyToManyField(AdHoc, blank=True, verbose_name="Ansible AdHoc任务")
    playbook_task = models.ManyToManyField(PlayBookTask, blank=True, verbose_name="Ansible Playbook任务")
    version = models.ForeignKey(DeployVersion, null=True, blank=True, on_delete=models.DO_NOTHING, verbose_name="任务版本")

    def __str__(self):
        return "{}:{}".format(self.name, self.version.version)

    class Meta:
        verbose_name = "任务列表"
        verbose_name_plural = verbose_name

devops/templates/devops/celery_task_log.html
{% load static %}
<head>
    <title>term.js</title>
    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/plugins/xterm/xterm.js' %}"></script>
    <link rel="stylesheet" href="{% static 'js/plugins/xterm/xterm.css' %}" />
    <style>
        body {
            background-color: black;
        }
        .xterm-rows {
            {#padding: 15px;#}
            font-family: "Bitstream Vera Sans Mono", Monaco, "Consolas", Courier, monospace;
            font-size: 13px;
        }
    </style>
</head>
    <div id="term" style="height: 100%;width: 100%">
    </div>

<script>
    var rowHeight = 18;
    var colWidth = 10;
    var mark = '';
    var url = "{% url 'api-devops:celery-task-log' pk=object.id %}";
    var term;
    var end = false;
    var error = false;
    var interval = 200;

    function calWinSize() {
        var t = $('#marker');
        {#rowHeight = 1.00 * t.height();#}
        {#colWidth = 1.00 * t.width() / 6;#}
    }
    function resize() {
        {#console.log(rowHeight, window.innerHeight);#}
        {#console.log(colWidth, window.innerWidth);#}
       var rows = Math.floor(window.innerHeight / rowHeight) - 1;
       var cols = Math.floor(window.innerWidth / colWidth) - 2;
       console.log(rows, cols);
       term.resize(cols, rows);
    }
    function requestAndWrite() {
        if (!end) {
            $.ajax({
                url: url + '?mark=' + mark,
                method: "GET",
                contentType: "application/json; charset=utf-8"
            }).done(function(data, textStatue, jqXHR) {
                if (jqXHR.status === 203) {
                    error = true;
                    term.write('.');
                    interval = 500;
                }
                if (jqXHR.status === 200){
                    term.write(data.data);
                    mark = data.mark;
                    if (data.end){
                        end = true
                    }
                }
            })
        }
    }
    $(document).ready(function () {
        term = new Terminal();
        term.open(document.getElementById('term'));
        term.resize(80, 24);
        resize();
        term.on('data', function (data) {
            {#term.write(data.replace('\r', '\r\n'))#}
            term.write(data);
        });
        window.onresize = function () {
            resize()
        };
        {#$('.terminal').detach().appendTo('#term');#}
        setInterval(function () {
            requestAndWrite()
        }, interval)
    });
</script>

devops/templates/devops/devops_index.html
{% extends '_base_list.html' %}
{% block content_left_head %}
    <div class="uc pull-left m-l-5 m-r-5">
        <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">功能列表
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li class="active"><a href="{% url 'devops:index' %}">任务中心</a></li>
                <li class=""><a href="{% url 'devops:play-task-list' %}">PlayBook任务列表</a></li>
                <li class="divider"></li>
                <li><a href="javascript:void(0)" class="">创建任务</a></li>
                <li><a href="javascript:void(0)" class="">功能2</a></li>
            </ul>
        </div>
    </div>
{% endblock %}
{% block table_search %}{% endblock %}
{% block table_container %}{% endblock %}
{% block content_bottom_left %}{% endblock %}
{% block custom_foot_js %}{% endblock %}

devops/templates/devops/file_list.html
{% extends '_base_list.html' %}
{% load i18n static %}
{% block custom_head_css_js %}
    <link href="{% static "css/plugins/datatables/datatables.min.css" %}" rel="stylesheet">
    <link href="{% static 'css/plugins/select2/select2.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/plugins/select2/select2.full.min.js' %}"></script>
    <script src="{% static "js/plugins/datatables/datatables.min.js" %}"></script>
    <style type="text/css">
        .select2-drop {
            z-index: 10050 !important;
        }


        /*防止select2不会自动失去焦点*/
        .select2-container {
            z-index: 16000 !important;
        }

        .select2-drop-mask {
            z-index: 15990 !important;
        }

        .select2-drop-active {
            z-index: 15995 !important;
        }
    </style>
{% endblock %}

{% block content_left_head %}
    <div class="uc pull-left m-l-5 m-r-5">
        <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">功能列表
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <!--<li class=""><a href="{% url 'devops:index' %}">任务中心</a></li>-->
                <!--<li class=""><a href="{% url 'devops:play-task-list' %}">PlayBook任务列表</a></li>-->
                <li class="active"><a href="{% url 'devops:filecheck' %}">对账文件检查状态</a></li>
                <li class="divider"></li>
                <li><a id="btn-create-form" href="javascript:void(0)" class="btn-create-form" data-toggle="modal" data-target="#FileCheckCreateModal">创建文件检查任务</a></li>
            </ul>
        </div>
    </div>
{% endblock %}
{% block table_search %}{% endblock %}
{% block table_container %}
    <table class="table table-striped table-bordered table-hover" id="task_table">
        <thead>
            <tr>
                <th class="text-center">任务ID</th>
                <th class="text-center">城市</th>
                <th class="text-center">渠道</th>
                <th class="text-center">节点IP</th>
                <th class="text-center">节点类型</th>
                <th class="text-center">上一次检查文件</th>
                <th class="text-center">上一次检查时间</th>
                <th class="text-center">下一次检查时间</th>
                <th class="text-center">文件日期正负</th>
                <th class="text-center">检查状态</th>
                <th class="text-center">定时任务状态</th>
                <th class="text-center">定时任务类型</th>
                <th class="text-center">操作</th>
            </tr>
        </thead>
    </table>

    <!-- FileCheckCreateModal -->
    <div class="modal fade" id="FileCheckCreateModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">创建检查任务</h4>
                </div>
                <form class="form-create" method="post">
                    {% csrf_token %}
                    <div class="modal-body form-group">

                        <h3>基本设置</h3>

                        <label for="city">企业名称</label>
                        <input class="form-control" type="text" id="city" name="city"/>
                        <label for="way">渠道</label>
                        <select class="form-control" id="way" name="way">
                            <option value="upload">上传</option>
                            <option value="download">下载</option>
                        </select>
                        <label for="file_path">文件路径</label>
                        <input class="form-control" type="text" id="file_path" name="file_path" placeholder="/path/to/"/>
                        <label for="file_format">文件格式</label>
                        <input class="form-control" type="text" id="file_format" name="file_format" placeholder="test.{}.txt"/>
                        <label for="time_format">日期格式</label>
                        <input class="form-control" type="text" id="time_format" name="time_format" placeholder="%Y-%m-%d"/>

                        <h3>节点设置</h3>

                        <div class="form-group">
                            <label class="" for="id_assets">{% trans 'Assets' %}</label>
                            <div class="">
                                <select data-placeholder="请选择" id="id_assets" name="asset_id" class="select2 form-control"
                                        tabindex="4" style="width:300px;">
                                </select>
                            </div>
                        </div>

                        <h3>任务设置</h3>

                        <label for="job_name">任务名称</label>
                        <input class="form-control" type="text" id="job_name" name="job_name"/>
                        <label for="trigger">触发器</label>
                        <select class="form-control" id="trigger" name="trigger">
                            <option value="">----</option>
                            <option value="cron">定时任务</option>
                            <option value="interval">循环任务</option>
                        </select>

                        <label for="crontab">时间表</label>
                        <input class="form-control" placeholder="请输入例: */1 2,4,5 * * *" type="text" id="crontab" name="crontab" disabled="disabled"/>
                        <label for="time">循环间隔</label>
                        <input class="form-control" placeholder="请输入间隔时间 单位:分钟" type="text" id="time" name="time" disabled="disabled"/>

                        <label for="time_delta">文件日期时间差</label>
                        <select class="form-control" id="time_delta" name="time_delta">
                            <option value="0">当天</option>
                            <option value="-2">2天前</option>
                            <option value="-1">1天前</option>
                            <option value="1">1天后</option>
                            <option value="2">2天后</option>
                        </select>


                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary btn-create-job">Save changes</button>
                    </div>
                </form>

            </div>
        </div>
    </div>

{% endblock %}
{% block content_bottom_left %}
{% endblock %}


{% block custom_foot_js %}
    <script>
        $('#trigger').on('change', function () {
            if($('#trigger').val()==='cron'){
                $('#crontab').removeAttr("disabled");
                $('#time').attr("disabled","disabled");
            }else if ($('#trigger').val()==='interval') {
                $('#time').removeAttr("disabled");
                $('#crontab').attr("disabled","disabled");
            }else {
                $('#crontab').attr("disabled","disabled");
                $('#time').attr("disabled","disabled");
            }
        });
        $(document).ready(function () {
            $.fn.modal.Constructor.prototype.enforceFocus = function() {};
            var the_url = "{% url 'api-devops:file_check_list' %}";
            $.get(the_url, function(result){
                console.log(result)
            });

            let options = {
                ele: $('#task_table'),
                columns: [
                    {data: 'job_id'}, {data: 'city'}, {data: "way"}, {data: "node_ip"}, {data: "node_type"}, {data: 'last_check_file'},{data: "last_check_time"},
                    {data: "next_run_time"}, {data: "time_delta"}, {data: "check_status"}, {data: "run_status"}, {data: 'trigger'}, {data: 'job_id'}
                    ],
                ajax_url: '{% url "api-devops:file_check_list" %}',
                columnDefs: [
                    {targets: 9, createdCell: function (td, cellData) {
                        if (cellData) {
                            let html = '<i class="fa fa-check text-navy"></i>';
                            $(td).html(html);
                        }else {
                            let html = '<i class="fa fa-times text-danger"></i>';
                            $(td).html(html);
                        }
                    }},
                    {targets: 10, createdCell: function (td, cellData) {
                        if (cellData) {
                            let html = '<i class="fa fa-check text-navy"></i>';
                            $(td).html(html);
                        }else {
                            let html = '<i class="fa fa-times text-danger"></i>';
                            $(td).html(html);
                        }
                    }},
                    {targets :12, createdCell: function (td, cellData) {
                        let delete_btn = '<a class="btn btn-xs btn-danger m-l-xs btn-delete" href="javascript:void(0)" job_id="99999">{% trans "Delete" %}</a>'.replace("99999", cellData);
                        let update_btn = '<a href="{% url "devops:filecheck-update" pk=DEFAULT_PK %}" class="btn btn-xs btn-primary m-l-xs btn-role-update">{% trans "Update" %}</a>'.replace('{{ DEFAULT_PK }}', cellData);
                        //console.log(cellData);
                        $(td).html(delete_btn + update_btn);
                    }}
                ]
            };
            var TaskTable = jumpserver.initDataTable(options);
        });

        $("body").on('click', '.btn-delete', function () {
            let job_id = $(this).attr('job_id');
            console.log(job_id);
            if(confirm("确定该删除任务?")){
                //确认后的任务
                let the_url ="{% url 'api-devops:file_check_delete' pk=DEFAULT_PK %}".replace('{{ DEFAULT_PK }}', job_id);
                $.ajax({
                    url: the_url,
                    async: false,
                    type: 'GET',
                    dataType: 'json',
                    contentType: "application/x-www-form-urlencoded",
                    success: function (result) {
                        alert(result.msg);
                        window.location.reload()
                    }
                });
            }
        });

        $("body").on('click', '.btn-create-job', function(){

            console.log("click");
            let form_data = $('.form-create').serializeArray();
            //alert(form_data);
            $.ajax({
                url: "{% url 'api-devops:file_check_add' %}",
                async: false,
                type: 'POST',
                dataType: 'json',
                contentType: "application/x-www-form-urlencoded",
                data: form_data,
                success: function (result) {
                    if (result.code === 200){
                        alert(result.msg);
                        window.location.reload()
                    }else{
                        alert(result.code + result.msg);
                    }
                },
                error: function (result) {
                    alert("Unknown error")
                }
            });
        });

        $('#FileCheckCreateModal').on('show.bs.modal', function (e) {

            $('#id_assets').select2({
                dropdownParent:$("#FileCheckCreateModal"),
                //ajax查询all assets
                ajax: {
                    url: '{% url 'api-devops:my-assets' %}',
                    dataType: 'json',
                    crossDomain: true,
                    processResults: function (data) {
                        let results = $(data).each(function (index, element) {
                            element.text = element.hostname + "(" + element.ip + ")"
                        });
                        return {results: results};//必须赋值给results并且必须返回一个obj
                    }
                }
            });

        })
    </script>
{% endblock %}